---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/auth/login":
    post:
      summary: login auth
      responses:
        '200':
          description: successful
  "/api/v1/auth/register":
    post:
      summary: register auth
      responses:
        '200':
          description: successful
  "/api/v1/auth/logout":
    post:
      summary: logout auth
      responses:
        '200':
          description: successful
  "/api/v1/blobs":
    post:
      summary: upload blob
      responses:
        '200':
          description: successful
  "/api/v1/blobs/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: get blob
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
