---
openapi: 3.0.1
info:
  title: Simple Drive API V1
  version: v1
components:
  contentType: application/json
  headers:
    contentType:
      description: content type
      schema:
        type: string
  securitySchemes:
    bearerAuth:
      description: JWT Token
      name: Authorization
      in: header
      type: bearer
      bearerFormat: JWT
paths:
  "/api/v1/blobs":
    post:
      summary: upload blob
      security:
      - bearerAuth:
          description: JWT Token
          name: Authorization
          in: header
          type: bearer
          bearerFormat: JWT
      parameters: []
      responses:
        '201':
          description: ''
        '401':
          description: unauthorized
  "/api/v1/blobs/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: get blob
      security:
      - bearerAuth: []
      parameters:
      - name: Authorization
        in: header
        required: true
        description: Bearer token
        schema:
          type: string
      responses:
        '200':
          description: successful
        '401':
          description: unauthorized
servers:
- url: http://{defaultHost}
  description: Local server
  variables:
    defaultHost:
      default: localhost:3000
